### ISSUE TITLE
ERROR: unable to create encoder input surface (err=-38)

### ISSUE THREAD

**Issue by roycezhc** [izacus/RoboGif#1]
I got this on the android 4.4.2 (API 19) emulator. Can you please let me know if I did anything wrong?

```
ADB Recorder v0.1
Starting recording on device...
Press Ctrl+C to stop recording.
ERROR: unable to create encoder input surface (err=-38)
Traceback (most recent call last):
  File "record.py", line 53, in <module>
    recorder.send_signal(signal.SIGTERM)
  File "/usr/lib/python2.7/subprocess.py", line 1554, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process
```

**Comment by izacus** [comment]
Unfortunately the `screenrecord` adb command doesn't work on the emulators (stock or Genymotion) because requires hardware acceleration / encoding support isn't implemented. Where's nothing much I can do about it, you'll need an actual device :(

**Comment by roycezhc** [comment]
Thanks :->
