### ISSUE TITLE
Add possibility to change quality parameters

### ISSUE THREAD

**Issue by vbauer** [izacus/RoboGif#4]
It would be very useful to minimize size of the output file and allow to configure output image size and count of frames. Now, util creates 5-15Mb images, I think it's too much.

PS: Thank you for this project.

**Comment by izacus** [comment]
Video quality parameter was added in https://github.com/izacus/RoboGif/commit/1a432f24a0e9cd0c3d497e954051cbbc96e61585, other parameters are available since sooner :)
